[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.coverage.run]
    branch = true
    source = ["./ropy"]

[tool.coverage.report]
    omit = [
        "./ropy/ignition/messages.py",
        "*tests*"
    ]

    exclude_lines = [
        "pragma: no cover",
        "raise NotImplementedError"
    ]
        